### ISSUE TITLE
Max Stack Size displays in new update

### ISSUE THREAD

**Issue by LePheel** [MadBuffoon/WeightBase#2]
Since the recent update, Max Stack Size is showing up again. Previously, there was no display for max stack size, it would instead only display the current stack.

**Comment by AzumattDev** [comment]
Fixed in #3 

> Since the recent update, Max Stack Size is showing up again. Previously, there was no display for max stack size, it would instead only display the current stack.

**Comment by MadBuffoon** [comment]
Fix in 1.1.1
